name: catolica
description: Exibe a programação da Semana de TI da Catolica

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: 1.1.1
  flutter_mobx: 1.1.0
  provider: 4.0.4
  rxdart: 0.23.1
  modal_progress_hud: ^0.1.3

  firebase_auth: 0.16.1
  cloud_firestore: 0.13.6
  firebase_storage: 3.1.6
  firebase_messaging: 6.0.16

  cached_network_image: 2.2.0+1

  image_picker: 0.6.7+2
  image_cropper: 1.2.3

  shared_preferences: 0.5.6+3

  flutter_masked_text: 0.8.0
  bot_toast: ^2.3.1
  intl: 0.16.1

  font_awesome_flutter: 8.8.1

  device_info: 0.4.2+4

  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.9.0
  mobx_codegen: 1.0.3

flutter:
  uses-material-design: true