name: catolica
description: Exibe a programação da Semana de TI da Catolica

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  redux: 4.0.0
  flutter_redux: 0.6.0
  provider: 4.0.4
  rxdart: 0.23.1

  shared_preferences: 0.5.6+3

  flutter_masked_text: 0.8.0
  bot_toast: ^2.3.1
  intl: 0.16.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true